### PR TITLE
Create React Todo App

### PR DESCRIPTION
**Pull request by Timbar09**
In this PR, I created a todo app using React

**Changes**

- Added a React form
- Implemented external CSS, inline CSS, and CSS modules to style the app
- Raised and handled events
- Used React life cycle methods.
- Implemented React icons
- Used React hooks
- Managed React state using Zustand library
- Added routing system
- Deployed app on GitHub Pages

### CODE REVIEW

**Review by mohisa302 — CHANGES_REQUESTED** [review]
# Status: Required Changes ♻️ ♻️ ♻️

Hi @Timbar09 ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

## Highlights

✅ You used Gitflow correctly 👍🏽
✅ All the functionality added👍🏽
✅ The app works fine as expected and all routes work fine 👍🏽

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by mohisa302** [comment]
I can't see any linters checks, please make sure you have added linters file ✔️ ✖️

**Comment by mohisa302** [comment]
please as mentioned in the requirements, add more details To your PR description 🖊️ 
`- Pull request should have a short summary describing introduced changes in more detail.`

**Comment by mohisa302** [comment]
https://github.com/Timbar09/React-Todo-App/blob/d44885ac29c344e4e5d414456b3299b1a3361e84/README.md?plain=1#L156-L160

- [optional] kindly do not forget to add mentioned tutorial link in the acknowledgment 🙏

**Comment by mohisa302** [comment]
https://github.com/Timbar09/React-Todo-App/blob/d44885ac29c344e4e5d414456b3299b1a3361e84/README.md?plain=1#L54-L57

- please make sure your default page is home as you can see in the picture 🔨 

image

**Comment by mohisa302** [comment]
https://github.com/Timbar09/React-Todo-App/blob/d44885ac29c344e4e5d414456b3299b1a3361e84/src/components/TodosLogic.jsx#L6-L19

- please get rid of unused code they make your code unclean 🧹

**Comment by mohisa302** [comment]
- please make sure your read-me content is the same as Micriverse read-me template. as you can see in the pictures you have not futures features part 🧾 
- your read me:
image

- Microverse read me:
image

**Comment by Timbar09** [comment]
Thanks for the review, @mohisa302. I'll apply the changes.

**Comment by Timbar09** [comment]
Hi, @Mohi.

I implemented most of the changes you requested, except for the linters.

I did not add linters because they were not part of the requirements and also because I built the React app using Vite which has some features that are not accustomed to the linter rules.

If you need further clarity please let me know.

Thanks. 😊

**Comment by mohisa302** [comment]
> Hi, @mohi.
> 
> I implemented most of the changes you requested, except for the linters.
> 
> I did not add linters because they were not part of the requirements and also because I built the React app using Vite which has some features that are not accustomed to the linter rules.
> 
> If you need further clarity please let me know.
> 
> Thanks. 😊


Hello @Timbar09 , you did a great effort so far good job 👏👏! however,  as you can see in the repo, instruction part, says that you should set up linters correctly, and also you can check it through [this link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/exercises/full_partner_review.md) which is the project document from Microverse. if there is any conflict with Vite you can use ignore ESlint for that specific files, although, our ESLINT linters and styles only check files with `jsx` and `js` formats, the only difference is in the kind of importation module in these files. the style doesn't differ from the RCA method. I saw some of the student's repo that used Vite and also passed Linters checks, so kindly please add those files and folders and reach out if you have any problems thanks. 
happy coding! 🎉

**Comment by Timbar09** [comment]
I just saw the requirement. I must have missed it. Thanks for pointing it out, @mohisa302.

I'll find a way to implement it.

**Comment by mohisa302** [comment]
> I just saw the requirement. I must have missed it. Thanks for pointing it out, @mohisa302.
> 
> I'll find a way to implement it.

Anytime @Timbar09, reach out if you face problem 🤞

**Review by mohisa302 — APPROVED** [review]
Hi @Timbar09  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@mohisa302** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
> Hi @Timbar09 ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  [  ](https://camo.githubusercontent.com/d8de195a08af080c4ae2fd36bfcf741de68f66af2162d291a21e113ce1b490fc/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966) [ ](https://camo.githubusercontent.com/d8de195a08af080c4ae2fd36bfcf741de68f66af2162d291a21e113ce1b490fc/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966)
> 
> ## Highlights
> Linters are passing 👍 The project is running successfully 👍 PR is well descriptive 👍
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me **@iambenkis** in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @mohisa302. You have been an awesome reviewer. 😊

**Comment by mohisa302** [comment]
> > Hi @Timbar09 ,
> > Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  [  ](https://camo.githubusercontent.com/d8de195a08af080c4ae2fd36bfcf741de68f66af2162d291a21e113ce1b490fc/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966) [ ](https://camo.githubusercontent.com/d8de195a08af080c4ae2fd36bfcf741de68f66af2162d291a21e113ce1b490fc/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966)
> > ## Highlights
> > Linters are passing 👍 The project is running successfully 👍 PR is well descriptive 👍
> > ## Optional suggestions
> > _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> > Cheers and Happy coding!👏👏👏
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me **@iambenkis** in your question so I can receive the notification.
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> Thank you @mohisa302. You have been an awesome reviewer. 😊

My pleasure @Timbar09 😉. I enjoyed working with you 😃 
Cheers and Happy coding!👏👏👏

**Pull request merged**
